NOISSUE - Add separate mqtts listener
mainflux/mproxy pull request #19
Opened 2020-08-20 17:09 UTC by blokovi

2020-08-20 21:17 UTC, drasko requested changes
I would also introduce one more check - how do I disable listener if I want for example TLS-only? So it would be better to check if the host is an empty string, which can be used as a flag to disable some of the listeners that mProxy spawns by default.

2020-09-01 08:14 UTC, blokovi commented
> I would also introduce one more check - how do I disable listener if I want for example TLS-only? So it would be better to check if the host is an empty string, which can be used as a flag to disable some of the listeners that mProxy spawns by default.

Added `MPROXY_CLIENT_TLS` environment variable that determines whether to include mqtts listener

2020-09-01 09:32 UTC, mteodor commented on pkg/session/session.go
> +		cert, err := clientCert(s.inbound)
what if `s==nil`?

2020-09-01 19:33 UTC, drasko commented
No need for `tls` branch any more. We know that we want this on the `master`, so please send PR over there. Also, please take remarks into account and fix them.

2020-09-02 15:34 UTC, blokovi commented on cmd/main.go
> +	// MQTTS
@dusanb94  Yes, that's right, now we have bool flag `MPROXY_CLIENT_TLS` that turns mqtts on or off (and mqtt is on reagrdless).
So, what do you suggest? When mqtts is on to turn mqtt off? Or to have another flag just for mqtt listener? Also we should keep in mind that there is http listener (for mqtt over ws), and we will have more listeners in future (secured and not)

2020-09-03 06:28 UTC, dusanb94 commented on cmd/main.go
> +	// MQTTS
Since this is the main method, it should not affect the future implementation of mGate. Having TLS switch to turn MQTTS and WSS on sounds intuitive, and having MQTT and WS off when MQTTS and WSS are on sounds good, as well.

2020-09-03 09:04 UTC, blokovi commented on cmd/main.go
> +	// MQTTS
Depending on `MPROXY_CLIENT_TLS` it will start only all secured (mqtts for now) or only all unsecured protocols (ws and mqtt for now)

2020-09-07 10:18 UTC, manuio commented on pkg/session/session.go
> +	errClient     = errors.New("error between mProxy and MQTT client")
This error messages could start with `failed to` and be more detailed

2020-09-10 11:59 UTC, closed without merging

2020-09-10 12:00 UTC, blokovi commented
PR sent to master: https://github.com/mainflux/mproxy/pull/22