NOISSUE - Add separate mqtts listener
mainflux/mproxy pull request #22
Opened 2020-09-10 11:59 UTC by blokovi

Add TLS listener, extract client cert and put it in client so external event handlers can manipulate with them

2020-09-10 13:15 UTC, mteodor submitted a review, later dismissed

2020-09-10 14:32 UTC, dusanb94 requested changes

2020-09-10 14:32 UTC, dusanb94 commented on README.md
> +| MPROXY_MQTT_HOST          | MQTT inbound (IN) connection host)             | 0.0.0.0   |
Please remove an extra `)`. You can also remove `(IN)` from inbound connection/port or add `(OUT)` for target conn/port.

2020-09-10 14:32 UTC, dusanb94 commented on pkg/mqtt/mqtt.go
> +		panic("failed to parse root certificate")
Why panic and not simply return an error?

2020-09-11 11:17 UTC, blokovi commented on pkg/mqtt/mqtt.go
> +		panic("failed to parse root certificate")
Ah, that remains from example in `crypto/x509` docs. Thanks

2020-09-11 12:23 UTC, dusanb94 approved these changes

2020-09-11 12:37 UTC, manuio approved these changes
LGTM

2020-09-11 12:37 UTC, merged