Add secure WS listener
mainflux/mproxy pull request #23
Opened 2020-09-16 12:19 UTC by blokovi

2020-09-18 10:19 UTC, dusanb94 commented on cmd/main.go
> +	defWSSPort        = "8081"
Since we have a client TLS flag, we don't need separate ports for WSS and MQTTS. However, we can discuss adding something like mTLS flag, since not everyone wants to run mutual authentication (in a separate PR).

2020-09-18 10:19 UTC, dusanb94 commented on pkg/websocket/websocket.go
> +func (p Proxy) certConfig() (tls.Config, error) {
Since both WS and MQTT use both `certConfig` and `session.ClientCert(conn)`, maybe we can extract those to a shared `tls` package.

2020-09-18 12:23 UTC, blokovi commented on cmd/main.go
> +	defWSSPort        = "8081"
Now yes. But with more protocols that  mProxy will support, we will probably have flags by protocol. So, maybe it will be possible to have both mqtt and mqtts turned on (like some mqtt brokers support 1883 and 8883 listeners at same time), so this per protocol port could be needed. What do you think?

2020-09-18 12:29 UTC, mteodor approved these changes

2020-09-18 12:34 UTC, dusanb94 commented on cmd/main.go
> +	defWSSPort        = "8081"
TBH, I would add it later if there is a need. At the moment, I don't think that we'll need it soon, but I leave it up to you.

2020-09-18 12:56 UTC, drasko requested changes

2020-09-18 12:56 UTC, drasko commented on pkg/websocket/websocket.go
> +	if !ok {
Can this be inlined?

2020-09-18 19:10 UTC, blokovi commented on pkg/websocket/websocket.go
> +func (p Proxy) certConfig() (tls.Config, error) {
Moved to new tls package.
Also, certificates' paths removed from Proxy struct

2020-09-18 19:10 UTC, blokovi commented on pkg/websocket/websocket.go
> +	if !ok {
Yes, thanks. Inlined.

2020-09-18 19:32 UTC, manuio commented on cmd/main.go
> +	http.Handle("/mqtt", wp.Handler())
Can we use  `cfg.wsTargetPath` here?

2020-09-18 19:35 UTC, manuio commented on pkg/mqtt/mqtt.go
> +		p.logger.Error("Failed to get client certificate, reason: " + err.Error())
I would simply use `Failed to get client certificate: `

2020-09-18 19:38 UTC, manuio requested changes

2020-09-18 19:38 UTC, manuio commented on pkg/session/session.go
> +	errClient = errors.New("error between mProxy and MQTT client")
Don't use "error" in an error message

2020-09-18 19:40 UTC, manuio commented on pkg/websocket/websocket.go
> +		p.logger.Error("Failed to get client certificate, reason: " + err.Error())
Same here about `, reason`

2020-09-19 06:54 UTC, blokovi commented on cmd/main.go
> +	http.Handle("/mqtt", wp.Handler())
Not same thing.
This is path where clients/devices contact mProxy.
But `wsTargetPath` is path where mProxy contacts mqtt broker. `wsTargetPath` must be set on path that broker is listening ws connection (mosquitto and verne both listen on `/mqtt` that's why that is default for `wsTargetPath`)

2020-09-19 07:46 UTC, manuio commented on cmd/main.go
> +	http.Handle("/mqtt", wp.Handler())
Something else then?

2020-09-19 08:35 UTC, blokovi commented on pkg/session/session.go
> +	errClient = errors.New("error between mProxy and MQTT client")
changed error messages

2020-09-19 08:35 UTC, blokovi commented on pkg/websocket/websocket.go
> +		p.logger.Error("Failed to get client certificate, reason: " + err.Error())
fixed

2020-09-19 08:35 UTC, blokovi commented on pkg/mqtt/mqtt.go
> +		p.logger.Error("Failed to get client certificate, reason: " + err.Error())
changed

2020-09-19 08:36 UTC, blokovi commented on cmd/main.go
> +	http.Handle("/mqtt", wp.Handler())
added new envars to make listen paths configurable

2020-09-20 22:12 UTC, drasko approved these changes
LGTM

2020-09-21 07:09 UTC, manuio approved these changes
LGTM

2020-09-21 07:10 UTC, merged