NOISSUE - Decouple mainflux/mproxy and mainflux/mainflux
mainflux/mproxy pull request #30
Opened 2022-09-14 17:00 UTC by manuio

Signed-off-by: Manuel Imperiale <manuel.imperiale@gmail.com>

2022-09-16 08:34 UTC, dborovcanin reviewed
We do not need to implement a logger. It's OK to use the Mainflux logger in examples - it's a separate package anyways. So, we only need a logger interface specified. The same goes for errors - error handling in mProxy is rather simple - can we avoid having a copy of the Mainflux errors package?

2022-09-16 10:41 UTC, manuio commented
@dborovcanin I'm not sure to understand. Logger is also used in the main.go. About errors package, we are using `New` and `Wrap` methods. Should we remove non used methods like `Contains`?

2022-09-16 11:41 UTC, dborovcanin commented
For logger, I meant simply defining the logger interface and taking implementation from Mainflux. In examples and in `main.go`, it's ok to have MF dependency because that's not something anyone will import.
For errors, I thought about completely removing that package and relying on pure Go errors because error handling is rather simple. Instead of `wrap`, for example, we can do something like (in session.go):
```go
func wrap(err error, dir direction) error {
	if err == io.EOF {
		return err
	}
	switch dir {
	case up:
		return errors.New(errClient.Error() + ":" + err.Error())
	case down:
		return errors.New(errBroker.Error() + ":" + err.Error())
	default:
		return err
	}
}
```

2022-09-26 10:31 UTC, dborovcanin requested changes

2022-09-26 10:31 UTC, dborovcanin commented on pkg/mqtt/mqtt.go
> +		return errors.New(errCreateListener.Error() + ":" + err.Error())
No need for this `errCreateListener`, return an error directly.

2022-09-26 10:31 UTC, dborovcanin commented on pkg/session/session.go
> +		return errors.New(errClient.Error() + ":" + err.Error())
No need for errors, you can use strings constants instead like:
```go
return errors.New(errClient + err.Error())
```
I quickly benchmarked `errors.New(errClient + err.Error())` vs `fmt.Errorf` and for this simple case, it looks like simple `+` is the most efficient.2

2022-09-26 19:06 UTC, dborovcanin approved these changes

2022-10-26 09:48 UTC, drasko approved these changes
LGTM

2022-10-26 09:49 UTC, merged