MF-35 - Replace Client on session handler
mainflux/mproxy pull request #36
Opened 2023-04-26 07:03 UTC by SammyOina

Pull request title should be `MF-XXX - description` or `NOISSUE - description` where XXX is ID of issue that this PR relate to.
Please review the [CONTRIBUTING.md](https://github.com/mainflux/mainflux/blob/master/CONTRIBUTING.md) file for detailed contributing guidelines.

### What does this do?
Replace client on handler interface

### Which issue(s) does this PR fix/relate to?
resolves #35 

### List any changes that modify/break current functionality
None

### Have you included tests for your changes?
No

### Did you document any new/modified functionality?
No

### Notes

2023-04-26 09:29 UTC, dborovcanin requested changes

2023-04-27 14:38 UTC, arvindh123 reviewed
LGTM

2023-04-27 18:31 UTC, drasko requested changes

2023-04-27 19:39 UTC, SammyOina commented on pkg/session/client.go
> +const mproxyClientKey ctxkey = 1
there's no particular reason it is one, the key can be any number, we're using an integer to save on memory used by the key for performance reasons

2023-04-28 09:13 UTC, rodneyosodo requested changes

2023-04-28 09:13 UTC, rodneyosodo commented on pkg/session/session.go
> +		p.Username = s.Client.ID
```suggestion
		p.Username = s.Client.Username
```

2023-04-28 11:15 UTC, SammyOina commented on pkg/session/client.go
> +const mproxyClientKey ctxkey = 1
I've added a comment to explain it

2023-04-28 11:17 UTC, rodneyosodo requested changes

2023-04-28 11:17 UTC, rodneyosodo commented on pkg/session/client.go
> +// ErrClientNotInContext failed to retrieve client from context
```suggestion
// ErrClientNotInContext indicates failed to retrieve client from context
```

2023-04-28 11:17 UTC, rodneyosodo commented on examples/simple/simple.go
> +		h.logger.Error("client is missing: " + err.Error())
Already err implies client is missing
```suggestion
		h.logger.Error(err.Error())
```

2023-04-28 11:17 UTC, rodneyosodo commented on pkg/session/client.go
> +func (c *Client) FromContext(ctx context.Context) error {
Why not ?

```go
func FromContext(ctx context.Context) (*Client, error)
```

2023-04-28 11:27 UTC, rodneyosodo requested changes
Update README

2023-05-09 11:18 UTC, rodneyosodo requested changes

2023-05-09 11:18 UTC, rodneyosodo commented on pkg/session/client.go
> +// ErrClientNotInContext failed to retrieve client from context
not yet addressed

2023-05-09 11:18 UTC, rodneyosodo commented on examples/simple/simple.go
> +		h.logger.Error("client is missing: " + err.Error())
not yet addressed

2023-05-09 13:02 UTC, SammyOina commented on pkg/session/session.go
> +		Client:   Client{Cert: cert},
probably from the linter, I have reverted

2023-05-11 11:52 UTC, dborovcanin requested changes

2023-05-11 11:52 UTC, dborovcanin commented on pkg/session/client.go
> +type ctxkey int
`ctxKey`

2023-05-11 11:52 UTC, dborovcanin commented on pkg/session/client.go
> +const mproxyClientKey ctxkey = 1
`clientKey`

2023-05-15 10:44 UTC, dborovcanin requested changes

2023-05-16 11:09 UTC, dborovcanin requested changes

2023-05-16 11:09 UTC, dborovcanin commented on pkg/session/stream.go
> +	}
We can revert it to something similar to what we have on `master` and move this code to `authorize` like:
```go
func authorize(ctx context.Context, pkt packets.ControlPacket, h Handler) error {
	switch p := pkt.(type) {
	case *packets.ConnectPacket:
		s, ok := FromContext(ctx)
		if !ok {
			return ErrNoSession
		}
		s.ID = p.ClientIdentifier
		s.Username = p.Username
		s.Password = p.Password

		ctx = NewContext(ctx, s)
		if err := h.AuthConnect(ctx); err != nil {
			return err
		}
		// Copy back to the packet in case values are changed by Event handler.
		// This is specific to CONN, as only that package type has credentials.
		p.ClientIdentifier = s.ID
		p.Username = s.Username
		p.Password = s.Password
		return nil
	case *packets.PublishPacket:
		return h.AuthPublish(ctx, &p.TopicName, &p.Payload)
	case *packets.SubscribePacket:
		return h.AuthSubscribe(ctx, &p.Topics)
	default:
		return nil
	}
}
```

2023-05-16 13:05 UTC, dborovcanin requested changes

2023-05-16 13:05 UTC, dborovcanin commented on pkg/session/stream.go
> +			ctx, err = authorize(ctx, pkt, h)
No need to return context here.

2023-05-16 13:18 UTC, dborovcanin approved these changes

2023-05-28 21:38 UTC, drasko requested changes

2023-05-28 21:38 UTC, drasko commented on pkg/session/stream.go
> +func stream(ctx context.Context, dir direction, r, w net.Conn, h Handler, errs chan error) {
@dborovcanin I find it a bit confusing that functions have the same names, although one is exported. Would this overloading be considered as a good practice in Go?

2023-05-29 08:58 UTC, dborovcanin commented on pkg/session/stream.go
> +func stream(ctx context.Context, dir direction, r, w net.Conn, h Handler, errs chan error) {
@drasko I don't see anything wrong with it, but we can rename it to `proxy` if you want. Or you can suggest another name.

2023-05-29 09:37 UTC, drasko approved these changes
LGTM

2023-05-29 09:37 UTC, merged