NOISSUE - Add issue and PR templates
mainflux/mproxy pull request #38
Opened 2023-06-12 13:01 UTC by SammyOina

### What does this do?
Add issue and PR templates
Add badges

### Which issue(s) does this PR fix/relate to?
None

### List any changes that modify/break current functionality
None

### Have you included tests for your changes?
No

### Did you document any new/modified functionality?
No

### Notes

2023-06-12 22:55 UTC, drasko approved these changes
LGTM

2023-06-16 11:34 UTC, dborovcanin approved these changes

2023-06-16 11:36 UTC, dborovcanin requested changes

2023-06-22 21:34 UTC, drasko approved these changes
LGTM

2023-06-22 21:35 UTC, merged