UV-267 - Support http/s proxying
mainflux/mproxy pull request #42
Opened 2023-09-28 13:48 UTC by SammyOina

### What does this do?
Add support for http proxy

### Which issue(s) does this PR fix/relate to?

### List any changes that modify/break current functionality

### Have you included tests for your changes?

### Did you document any new/modified functionality?

### Notes

2023-09-29 15:06 UTC, rodneyosodo requested changes

2023-09-29 15:06 UTC, rodneyosodo commented on cmd/main.go
> +func proxyHTTPs(ctx context.Context, cfg HTTPConfig, logger mflog.Logger, handler session.Handler, errs chan error) {
```suggestion
func proxyHTTPS(ctx context.Context, cfg HTTPConfig, logger mflog.Logger, handler session.Handler, errs chan error) {
```

2023-09-29 15:06 UTC, rodneyosodo commented on cmd/main.go
> +	httpConfig HTTPConfig
```suggestion
	httpHost	string
	httpPort	string
	httpTargetHost	string
```
To be the same as other configs

2023-10-10 21:47 UTC, dborovcanin requested changes

2023-10-10 21:47 UTC, dborovcanin commented on pkg/http/http.go
> +	event   session.Handler
Rename to `session`.

2023-10-12 09:20 UTC, dborovcanin requested changes

2023-10-12 09:20 UTC, dborovcanin commented on pkg/http/http.go
> +	r.Body = io.NopCloser(bytes.NewBuffer(payload))
Add a quick explanation: We need to reset the body here so that the proxy can safely copy it now that it has been read.

2023-10-12 09:20 UTC, dborovcanin commented on pkg/http/http.go
> +	}()
Check if this call is needed now that we have a NopCloser that effectively does nothing on `Close()`.

2023-10-12 09:35 UTC, SammyOina commented on pkg/http/http.go
> +	}()
I have removed it, since it does not do anything

2023-10-12 09:56 UTC, dborovcanin approved these changes

2023-10-12 10:01 UTC, drasko approved these changes
LGTM

2023-10-12 12:23 UTC, merged